# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# executors:
#     with-chrome:
# #   chrome80-ff72:
#     docker:
#       - image: 'cypress/browsers:node13.6.0-chrome80-ff72'
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           executor: with-chrome
#           browser: chrome
#           store_artifacts: true

version: 2.1
orbs:
  # use latest 1.x.y version of the orb
  # best practice is to use an exact version
  cypress: cypress-io/cypress@1.16.1
  node: circleci/node@1.1

executors:
  chrome80-ff72:
    docker:
      - image: 'cypress/browsers:node13.6.0-chrome80-ff72'
      
workflows:
  build:
    jobs:
      - cypress/run:
      command:
      echo 'export EMAIL=${EMAIL}' >> $NODE_ENV
      echo 'export PASSWORD=${PASSWORD}' >> $NODE_ENV
          executor: chrome80-ff72
          browser: chrome
          store_artifacts: true
